name: Deploy PROD
on:
  push:
    branches: [main]
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/bortolato/www/Gauntlet-Challenge
            git stash -u
            git pull origin main
            git stash pop
            npm ci
            npm --workspace frontend run build
